name: docs

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
    tags:
      - 'docs-*'
  workflow_dispatch:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get latest tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: tag_name
      - uses: frabert/replace-string-action@v2
        if: steps.tag_name.outputs.tag != ''
        id: replace
        with:
          pattern: "docs-(.*)"
          string: "${{ steps.tag_name.outputs.tag }}"
          replace-with: '$1'
      - name: print tag_name
        if: ${{ success() }}
        run: echo tag_name ${{ steps.replace.outputs.replaced }}
      - uses: gradle/gradle-build-action@v2
        if: ${{ success() }}
      - name: Build dokka
        if: ${{ success() }}
        run: chmod +x gradlew &&./gradlew :openapi-sdk:dokkaGfm --no-daemon --stacktrace
      - uses: actions/setup-python@v4
        if: ${{ success() }}
        with:
          python-version: 3.x
      - name: pip install
        if: ${{ success() }}
        run: |
          pip install mkdocs-material=="9.*"
          pip install jieba
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mike
          git config user.name yuefeng
          git config user.email mcxinyu@foxmail.com
      #      - run: mkdocs gh-deploy --force
      - name: deploy
        if: ${{ success() }}
        run: |
          mike deploy --push -u ${{ steps.replace.outputs.replaced }} latest
          mike set-default --push latest
          mike list