name: docs

on:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gradle/gradle-build-action@v2
      - name: Build dokka
        run: chmod +x gradlew &&./gradlew :openapi-sdk:dokkaGfm --no-daemon --stacktrace
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material=="9.*"
          pip install jieba
          pip install mkdocs-git-revision-date-localized-plugin
          git config user.name yuefeng
          git config user.email mcxinyu@foxmail.com
      - run: mkdocs gh-deploy --force